### ISSUE TITLE
ImportError: cannot import name Serializer

### ISSUE THREAD

**Issue by KateLyndegaard** [greedo/python-xbrl#31]
Hi,
I've imported the latest updates from git and checked all of the requirements but I'm still getting this error:

Traceback (most recent call last):
  File "C:\Users\kate\Anaconda2\Lib\site-packages\pythonwin\pywin\framework\scriptutils.py", line 326, in RunScript
    exec codeObject in __main__.__dict__
  File "C:\Users\kate\Dropbox\CVR\Regnskab.py", line 15, in <module>
    import xbrl
  File "C:\Users\kate\Anaconda2\lib\site-packages\xbrl\__init__.py", line 8, in <module>
    from .xbrl import XBRLParser, GAAP, GAAPSerializer, XBRLParserException
  File "C:\Users\kate\Anaconda2\lib\site-packages\xbrl\xbrl.py", line 5, in <module>
    from marshmallow import Serializer, fields
ImportError: cannot import name Serializer

Do you have any idea how I can fix this? I'd like to use the library. Thanks.

**Comment by KateLyndegaard** [comment]
Sorry, solved the issue by reading issue #21.
