### ISSUE TITLE
in python-xbrl v1.1.0, marshmallow version 3.0.0.b7, error: has not object "Serializer" 

### ISSUE THREAD

**Issue by pinnaclesystemsgroup** [greedo/python-xbrl#43]
get_xbrl_data.py:Line #3 > from xbrl import XBRLParser, GAAP, GAAPSerializer

xbrl/__init__.py: Line #8 > from .xbrl import XBRLParser, GAAP, GAAPSerializer, XBRLParserException

Runtime ERROR:

/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/.../PyCharmprojects/xbrlpy/**get_xbrl_data.py**
Traceback (most recent call last):
  File "/Users/.../PyCharmprojects/xbrlpy/**get_xbrl_data.py**", line 3, in <module>
    from xbrl import XBRLParser, GAAP, GAAPSerializer
  File "/usr/local/lib/python2.7/site-packages/**xbrl/__init__.py**", line 8, in <module>
    from .xbrl import XBRLParser, GAAP, GAAPSerializer, XBRLParserException
  File "/usr/local/lib/python2.7/site-packages/xbrl/**xbrl.py"**, line 5, in <module>
    from marshmallow import Serializer, fields
ImportError: cannot import name Serializer

**Comment by greedo** [comment]
This maybe fixed now with the upgrade. I'll investigate thanks @pinnaclesystemsgroup
